### ISSUE TITLE
[AMP] Invalid layout property found in AMP tag (Critical issue)

### ISSUE THREAD

**Issue by Poliuk** [frontity/saturn-theme#62]
Fix invalid layout properties in your AMP tags. AMP pages with invalid layout property may appear in Google search results without AMP-specific display features.

List of pages with the issue: https://drive.google.com/file/d/1OCvDEh-CMxfv2_i6cyrOTpcCTVAwV--6/view?usp=sharing

**Please mention me once the issue is resolved so I can get back with the customer**

**Comment by orballo** [comment]
@Poliuk we have two different problems here, one is that we don't have support for soundcloud yet, and another one is that iframes in AMP should have always a src with `https` not `http`. We can fix the first one if you want me to build a new component to support soundcloud in AMP. But the second one is a problem that the costumer has to fix in their sites, because not always changing the url from `http` to `https` works, as in Cadena SER for example, the `https` url doesn't serve anything.

**Comment by Poliuk** [comment]
@orballo thanks for the research. 

Is it easy to have a list of the URLS containing a iframe with http? So I can write directly to the customer telling them that is their responsibility to fix it. 

Regarding the `soundcloud` component, If I'm not wrong there's already [official support for it](https://www.ampproject.org/docs/reference/components/amp-soundcloud), so It shouldn't take long.  @luisherranz Do you think we should implement it now as it is already throwing errors in live sites?

**Comment by luisherranz** [comment]
> Do you think we should implement it now as it is already throwing errors in live sites?

Sure, we should support what AMP supports.

**Comment by orballo** [comment]
Oki doki

**Comment by Poliuk** [comment]
@orballo as for the iframe issues. I wait for a list of URLS with conflics

**Comment by orballo** [comment]
@Poliuk The URLs from Cadena SER are the ones I found not serving under `https`. For example: `http://play.cadenaser.com/widget/audio/024RD010000000046706/`.
